#include <iostream>
using namespace std;
main(){
float num1;
float num2;
float num3;
float num4;
float num5;
float num6;
float num7;
float num8;
float num9;
float num10;
float num11;
float num12;
float num13;
float num14;
float num15;
float result1;
float result2;
float result3;
float result;
cout << "Enter Num1: "  ;
cin >> num1;
cout << "Enter Num2: "  ;
cin >> num2;
cout << "Enter Num3: "  ;
cin >> num3;
cout << "Enter Num4: "  ;
cin >> num4;
cout << "Enter Num5: "  ;
cin >> num5;
cout << "Enter Num6: "  ;
cin >> num6;
cout << "Enter Num7: "  ;
cin >> num7;
cout << "Enter Num8: "  ;
cin >> num8;
cout << "Enter Num9: "  ;
cin >> num9;
cout << "Enter Num10: "  ;
cin >> num10;
cout << "Enter Num11: "  ;
cin >> num11;
cout << "Enter Num12: "  ;
cin >> num12;
cout << "Enter Num13: "  ;
cin >> num13;
cout << "Enter Num14: "  ;
cin >> num14;
cout << "Enter Num15: "  ;
cin >> num15;
result1 = ( num1 + num2 + num3 + num4 + num5 ) ;
result2 = ( num6 - num7 - num8 - num9 - num10 ); 
result3 = ( num11 * num12 * num13 * num14 * num15 );
result = ( result1 + result2 ) - result3 ;
cout << "result1" << result1 ;
cout << "result2" << result2 ;
cout << "result3" << result3 ;
cout << "result" << result;
}